- name: Fetch Raspberry pi model
  slurp:
    src: "/sys/firmware/devicetree/base/model"
  register: rpi_model_data

- name: Set Raspberry Pi model
  ansible.builtin.set_fact:
     rpi_model: "{{ rpi_model_data['content'] | b64decode }}"

- name: Install Chromium
  package: 
      name: chromium-browser
      state: latest

- name: Install scrot
  package:
      name: scrot
      state: latest
 
- name: Install feh to display an image
  package:
      name: feh
      state: latest

- name: Install wmctrl to control windows
  package:
      name: wmctrl
      state: latest

- name: Install unclutter to get the mouse pointer to disappear
  package:
      name: unclutter
      state: latest

- name: Install python-uinput to fake keystrokes in the browser
  pip: 
     executable: /usr/bin/pip3
     name: python-uinput

- name: Load the uinput module to fake keystrokes
  lineinfile:
     dest: /etc/modules
     create: true
     line: "uinput"

- name: Install calendar start script
  copy:
     src: startup.sh
     dest: /home/pi/startup.sh
     mode: '0755'
     owner: pi

- name: Install calendar restart script
  copy:
     src: restart.sh
     dest: /home/pi/restart.sh
     mode: '0755'
     owner: pi

- name: Install refresh_cal script to scroll to the right spot on the calendar periodically
  copy:
     src: refresh_cal
     dest: /home/pi/refresh_cal
     mode: '0755'
     owner: pi

- name: Install reload_cal script
  copy:
     src: reload_cal
     dest: /home/pi/reload_cal
  when: false

- name: Job to restart calendar hourly
  cron: 
    user: pi
    name: "Restart calendar"
    minute: "0"
    job: "/home/pi/restart.sh 2>&1 >/dev/null"

# This last one turns out not to be necesary because Google Calendar updates automatically
- name: Job to refresh calendar by the minute
  cron:
    name: "Refresh calendar"
    job: "/home/pi/refresh_cal"
  when: false

- name: Autostart folder for LXDE
  file:
    path: "/home/pi/.config/autostart"
    state: directory
    owner: pi
    mode: '0755' 

- name: Autostart the calendar on boot
  copy:
     src: calendar.desktop
     dest: /home/pi/.config/autostart/calendar.desktop
     mode: '0644'
     owner: pi

- name: Remove default graphical screensaver config
  lineinfile:
     dest: /etc/xdg/lxsession/LXDE-pi/autostart
     state: absent
     line: "@xscreensaver -no-splash"

- name: Turn off screensaver in LXDE autostart
  template:
     src: autostart-no-screensaver
     dest: /etc/xdg/lxsession/LXDE-pi/autostart
     mode: '0644'
     owner: pi
     group: root
  when: ( DPMS_TIMEOUT_MIN | int ) <= 0

- name: Copy the script to monitor PIR sensor
  copy:
     src: pirMonitor
     dest: /home/pi/pirMonitor
     mode: '755'
     owner: pi
     group: pi
  when: ( DPMS_TIMEOUT_MIN | int ) > 0

- name: Turn on screensaver in LXDE autostart
  template:
     src: autostart-with-DPMS
     dest: /etc/xdg/lxsession/LXDE-pi/autostart
     mode: '0644'
     owner: pi
     group: root
  when: ( DPMS_TIMEOUT_MIN | int ) > 0
